"""empty message

Revision ID: 174400896450
Revises: f31c22cdadb1
Create Date: 2018-09-04 01:44:35.289821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174400896450'
down_revision = 'f31c22cdadb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('models', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('models', sa.Column('weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'weight')
    op.drop_column('models', 'height')
    op.drop_column('models', 'age')
    # ### end Alembic commands ###
