"""empty message

Revision ID: 23c5319f0069
Revises: da41ed9cd2d2
Create Date: 2018-08-29 07:43:02.524030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c5319f0069'
down_revision = 'da41ed9cd2d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('model_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'photos', 'models', ['model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_column('photos', 'model_id')
    # ### end Alembic commands ###
