"""empty message

Revision ID: 569d772e419e
Revises: 589678448e0d
Create Date: 2018-08-29 08:13:39.877166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569d772e419e'
down_revision = '589678448e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('photo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'models', 'photos', ['photo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'models', type_='foreignkey')
    op.drop_column('models', 'photo_id')
    # ### end Alembic commands ###
