"""empty message

Revision ID: 589678448e0d
Revises: e84b1560b46b
Create Date: 2018-08-29 08:07:06.866084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589678448e0d'
down_revision = 'e84b1560b46b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('model_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'photos', 'models', ['model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_column('photos', 'model_id')
    # ### end Alembic commands ###
