"""empty message

Revision ID: 6806cba1823b
Revises: c35c68c7714d
Create Date: 2018-08-06 12:33:06.385367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6806cba1823b'
down_revision = 'c35c68c7714d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_column('users', 'name')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
