"""empty message

Revision ID: c7fa6c5a5ad6
Revises: 452fd5f203a5
Create Date: 2018-08-24 11:07:08.452237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7fa6c5a5ad6'
down_revision = '452fd5f203a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('is_accepted_by_admin', sa.Boolean(), nullable=True))
    op.add_column('models', sa.Column('is_accepted_by_root', sa.Boolean(), nullable=True))
    op.drop_column('models', 'accepted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('accepted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('models', 'is_accepted_by_root')
    op.drop_column('models', 'is_accepted_by_admin')
    # ### end Alembic commands ###
