"""empty message

Revision ID: da41ed9cd2d2
Revises: e9cda17649ac
Create Date: 2018-08-27 15:32:33.424464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da41ed9cd2d2'
down_revision = 'e9cda17649ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('city', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
