"""empty message

Revision ID: e9cda17649ac
Revises: c7fa6c5a5ad6
Create Date: 2018-08-27 11:52:11.708925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9cda17649ac'
down_revision = 'c7fa6c5a5ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'is_archived')
    # ### end Alembic commands ###
