"""empty message

Revision ID: f31c22cdadb1
Revises: 569d772e419e
Create Date: 2018-08-29 08:36:13.179506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31c22cdadb1'
down_revision = '569d772e419e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('models_avatar_id_fkey', 'models', type_='foreignkey')
    op.drop_constraint('models_photo_id_fkey', 'models', type_='foreignkey')
    op.drop_column('models', 'photo_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('photo_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('models_photo_id_fkey', 'models', 'photos', ['photo_id'], ['id'])
    op.create_foreign_key('models_avatar_id_fkey', 'models', 'photos', ['avatar_id'], ['id'])
    # ### end Alembic commands ###
